name: LPDD Pipeline

on:
  # Triggers the workflow on push or pull request events to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - chore/config-jest # For testing/demo. Will remove after merge

  # Allows you to run this workflow manually from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  # Job to build and test Next.js application
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21" # Set the node version for your project, adjust if necessary

      # Step 3: Install dependencies using npm or yarn (depending on your project)
      - name: Install dependencies
        run: npm ci
        # If you use yarn, uncomment the next line and remove the npm install line
        # run: yarn install

      # Step 4: Build the Next.js application
      - name: Build Next.js app
        run: npm run build
        # For yarn users:
        # run: yarn build

      # Step 5: Run tests (if you have tests configured)
      - name: Run Tests
        run: npm run test
        # For yarn users:
        # run: yarn test
